"""The acceptance criteria of the combined spec.

One test per acceptance criterion. AT-R1 to AT-R13 are the representation tests;
AT-K1 to AT-K10 are the kernel tests. A criterion whose subject is not built yet
is skipped with the delivery phase that owns it named, so the suite reports what
is actually demonstrated rather than implying more.
"""

import subprocess
import sys
from dataclasses import replace
from pathlib import Path

import pytest

from conftest import FIXED_TIME, PROJECT, REGULATOR, WATTS, conductive, tool_provenance

from fang.constraints import CheckStatus, Constraint, Literal, Ref, le
from fang.diagnostics import FangError
from fang.diff import ChangeClass, diff
from fang.entities import (
    Component,
    Connection,
    ConnectionKind,
    Evidence,
    Requirement,
    RequirementState,
)
from fang.graph import (
    AddEntity,
    CheckResult,
    KernelGraph,
    SetParameter,
    Snapshot,
    Transaction,
    ingest_external_results,
    materialize,
    Realization,
)
from fang.identity import authored, derive, imported
from fang.queries import causing_requirements
from fang.serialization import canonical_bytes, canonical_record_stream
from fang.topology import TopologyConstraint, TopologyMode
from fang.units import Quantity
from fang.validation import StateTransition, check_schema_version, check_transition, validate
from fang.values import Value

EXAMPLES = Path(__file__).resolve().parent.parent / "examples"

#: Every stage of the roadmap has landed, so no criterion is deferred any more.
#: A criterion that cannot be demonstrated would skip with the reason named here.


# ==========================================================================
# Representation acceptance tests
# ==========================================================================


def test_at_r1_import_of_a_representative_kicad_project_without_unreported_loss():
    """AT-R1: a real netlist imports, and any loss is reported rather than silent."""
    from fang.kicad import read_netlist

    text = (EXAMPLES / "imported" / "reference.net").read_text()
    result = read_netlist(text, project_id=PROJECT, source="reference.net")

    # Everything the file carries is recovered.
    designators = {
        e.designator
        for e in result.entities.values()
        if isinstance(e, Component)
    }
    assert designators == {"U1", "C1", "C2", "R1", "J1"}
    # Every net the file names survives with its own name.
    from fang.entities import Net

    assert {alias for e in result.entities.values() if isinstance(e, Net)
            for alias in e.aliases} == {"+3V3", "GND", "NRST"}

    # The symbol-library block carries no connectivity and this adapter does not
    # model it. That is reported rather than dropped, which is the whole point.
    assert not result.report.lossless
    assert {item.construct for item in result.report.unrepresented} == {"libparts"}


def test_at_r2_byte_identical_reserialization_of_unchanged_state(snapshot):
    """AT-R2: reserializing unchanged state produces byte-identical output."""
    assert canonical_bytes(snapshot.as_dict()) == canonical_bytes(snapshot.as_dict())
    assert canonical_record_stream(snapshot.records()) == canonical_record_stream(
        snapshot.records()
    )


def test_at_r3_stable_ids_across_non_semantic_cad_formatting_changes():
    """AT-R3: reformatting a file changes no identifier."""
    from fang.kicad import read_netlist

    text = (EXAMPLES / "imported" / "reference.net").read_text()
    # A non-semantic reformat: different whitespace, different line breaks, and
    # a comment. None of it is meaning.
    reformatted = "; regenerated by another tool\n" + " ".join(text.split())

    first = read_netlist(text, project_id=PROJECT, source="reference.net")
    second = read_netlist(reformatted, project_id=PROJECT, source="reference.net")
    assert set(first.entities) == set(second.entities)


def test_at_r4_semantic_diff_of_component_connectivity_and_constraint_changes(snapshot):
    """AT-R4: all three change families are classified."""
    before = dict(snapshot.entities)
    after = dict(before)

    after["CMP-NEW"] = Component(authored("CMP-NEW"), designator="U3")
    after["CN-1"] = Connection(
        authored("CN-1"),
        connection_kind=ConnectionKind.POWER,
        source="RAIL-3V3",
        target=REGULATOR,
    )
    after["RULE-1"] = Constraint(
        authored("RULE-1"),
        constraint_kind="max_power_dissipation",
        targets=(REGULATOR,),
        expression=le(Ref(REGULATOR, "power_dissipation", WATTS), Literal.of(Quantity.scalar("1", "W"))),
    )

    classes = {c.type for c in diff(before, after)}
    assert ChangeClass.COMPONENT_ADDED in classes
    assert ChangeClass.CONNECTION_ADDED in classes
    assert ChangeClass.ENTITY_ADDED in classes or ChangeClass.CONSTRAINT_CHANGED in classes

    # And a constraint that changes in place is classified as a constraint change.
    later = dict(after)
    later["RULE-1"] = replace(after["RULE-1"], verification_status=CheckStatus.PASS)
    assert ChangeClass.VERIFICATION_STATUS_CHANGED in {c.type for c in diff(after, later)}


def test_at_r5_traceability_to_the_originating_requirement_or_decision(snapshot):
    """AT-R5: a generated component traces to the requirement that caused it."""
    assert causing_requirements(snapshot, REGULATOR) == ["REQ-PWR-001"]


def test_at_r6_rejection_of_dangling_required_references():
    """AT-R6."""
    connection = Connection(
        authored("CN-1"),
        connection_kind=ConnectionKind.POWER,
        source="CMP-A",
        target="CMP-ABSENT",
    )
    report = validate({"CN-1": connection, "CMP-A": Component(authored("CMP-A"))})
    assert not report.ok
    assert any(d.code == "ELAB-0006" for d in report.diagnostics)


def test_at_r7_explicit_reporting_of_lossy_adapter_operations():
    """AT-R7."""
    from fang.kicad import read_netlist

    text = """
    (export "version" "E"
      (components (comp (ref "R1") (value "10k") (thermal_model "x")))
      (nets)
      (proprietary_block "data"))
    """
    result = read_netlist(text, project_id=PROJECT, source="lossy.net")
    assert not result.report.lossless
    constructs = {item.construct for item in result.report.unrepresented}
    assert {"proprietary_block", "thermal_model"} <= constructs
    for item in result.report.unrepresented:
        assert item.where                      # each loss names where it happened
    assert all(d.code == "IMPORT-0001" for d in result.report.diagnostics())


def test_at_r8_identical_derived_ids_across_machines_and_a_rename_reported_as_a_rename():
    """AT-R8: derivation is machine-independent, and a rename is a rename."""
    script = (
        "from fang.identity import derive;"
        "print(derive('PRJ-1','component','system.power.buck_3v3.U1').id)"
    )
    outputs = {
        subprocess.run(
            [sys.executable, "-c", script],
            capture_output=True,
            text=True,
            env={"PYTHONHASHSEED": seed, "PATH": "/usr/bin:/bin"},
            check=True,
        ).stdout.strip()
        for seed in ("0", "1", "99")
    }
    assert len(outputs) == 1
    assert outputs.pop() == derive("PRJ-1", "component", "system.power.buck_3v3.U1").id

    identity = derive(PROJECT, "component", "system.x.u1")
    before = {identity.id: Component(identity, provenance=tool_provenance())}
    after = {
        identity.id: Component(
            replace(identity, display_name="Renamed"), provenance=tool_provenance()
        )
    }
    changes = list(diff(before, after))
    assert [c.type for c in changes] == [ChangeClass.RENAME]
    assert ChangeClass.COMPONENT_ADDED not in {c.type for c in changes}
    assert ChangeClass.COMPONENT_REMOVED not in {c.type for c in changes}


def test_at_r9_a_conforming_provenance_record_on_every_derived_or_imported_entity():
    """AT-R9."""
    derived_without = Component(derive("PRJ-1", "component", "system.x.u1"))
    assert not validate({derived_without.id: derived_without}).ok

    derived_with = Component(
        derive("PRJ-1", "component", "system.x.u1"), provenance=tool_provenance()
    )
    assert validate({derived_with.id: derived_with}).ok

    imported_without = Component(imported("CMP-I", external_id="/ext/1"))
    assert not validate({imported_without.id: imported_without}).ok


def test_at_r10_rejection_of_an_unimplemented_major_schema_version():
    """AT-R10."""
    with pytest.raises(FangError) as caught:
        check_schema_version("2.0")
    assert caught.value.diagnostic.code == "ELAB-0009"
    check_schema_version("1.0")  # a known major version is accepted


def test_at_r11_rejection_of_a_dimensionally_invalid_expression_where_it_is_written():
    """AT-R11: rejected at construction, never carried into evaluation."""
    with pytest.raises(FangError) as caught:
        le(Ref("CMP-1", "voltage", Quantity.scalar("0", "V").dimension),
           Literal.of(Quantity.scalar("1", "A")))
    assert caught.value.diagnostic.code == "UNIT-0001"


def test_at_r12_an_undecided_result_is_reported_as_undecided(snapshot):
    """AT-R12: never a pass, never a failure."""
    rule = Constraint(
        authored("RULE-U"),
        constraint_kind="max_power_dissipation",
        targets=(REGULATOR,),
        expression=le(Ref(REGULATOR, "not_measured", WATTS), Literal.of(Quantity.scalar("1", "W"))),
    )
    status = rule.evaluate(snapshot.resolver())
    assert status is CheckStatus.UNKNOWN
    assert status is not CheckStatus.PASS
    assert status is not CheckStatus.FAIL


def test_at_r13_rejection_of_an_invalid_requirement_state_transition():
    """AT-R13."""
    problems = check_transition(
        StateTransition("REQ-1", RequirementState.MISSING, RequirementState.VERIFIED, "a", "r")
    )
    assert any(p.code == "ELAB-0007" for p in problems)


# ==========================================================================
# Kernel acceptance tests
# ==========================================================================


def test_at_k1_import_of_an_existing_project_with_every_mismatch_reported():
    """AT-K1: every mismatch against the source netlist is reported."""
    from fang.kicad import read_netlist
    from fang.netlist import compile_netlist
    from fang.sexpr import parse

    text = (EXAMPLES / "imported" / "reference.net").read_text()
    result = read_netlist(text, project_id=PROJECT, source="reference.net")
    snapshot = Snapshot(PROJECT, "REV-IMPORT", result.entities)
    recompiled = compile_netlist(snapshot)

    source = parse(text)
    source_refs = {
        comp.value("ref") for comp in source.child("components").children("comp")
    }
    recompiled_refs = {c.designator for c in recompiled.components}
    assert source_refs == recompiled_refs, "a component mismatch would appear here"

    source_nets = {
        net.pairs().get("name") for net in source.child("nets").children("net")
    }
    assert source_nets == {net.name for net in recompiled.nets}
    # Import fidelity is measured here, and what could not be modelled is named.
    assert result.report.recovered > 0
    assert isinstance(result.report.as_dict()["unrepresented"], list)


def test_at_k2_stable_identifiers_across_re_elaboration_of_unchanged_sources():
    """AT-K2: the re-elaboration half; repeated import is Phase 2."""
    def elaborate():
        return [
            derive(PROJECT, "component", path).id
            for path in ("system.power.buck_3v3.U1", "system.logic.mcu", "system.power.3v3")
        ]

    assert elaborate() == elaborate()


def test_at_k3_byte_identical_snapshots_from_identical_source_lock_and_compiler(snapshot):
    """AT-K3: for the record stream as well as for the single document."""
    twin = Snapshot(
        snapshot.project_id,
        snapshot.revision_id,
        dict(snapshot.entities),
        lock_id=snapshot.lock_id,
    )
    assert canonical_bytes(snapshot.as_dict()) == canonical_bytes(twin.as_dict())
    assert canonical_record_stream(snapshot.records()) == canonical_record_stream(twin.records())
    assert snapshot.hash == twin.hash

    # A different lock identity is a different snapshot, as it must be.
    assert replace(snapshot, lock_id="other").hash != snapshot.hash


def test_at_k4_reproducible_interconnect_power_and_ground_views(snapshot):
    """AT-K4: no connection absent from the snapshot, and identical on rerun."""
    from fang.views import view

    for name in ("interconnect", "power", "ground"):
        graph = view(snapshot, name)
        for edge in graph.edges:
            assert edge.id in snapshot.entities
            assert edge.source in snapshot.entities
            assert edge.target in snapshot.entities
        for node in graph.nodes:
            assert node.id in snapshot.entities
        assert view(snapshot, name).as_dict() == graph.as_dict()


def test_at_k5_a_topology_check_names_each_unpermitted_path():
    """AT-K5: the topology half; the ground view is Phase 3."""
    entities = {}
    for connection in (
        conductive("CN-1", "DOM-LOGIC", "NET-MOTOR-STAR"),
        conductive("CN-2", "DOM-MOTOR", "NET-MOTOR-STAR"),
        conductive("CN-3", "DOM-LOGIC", "NET-CHASSIS"),
        conductive("CN-4", "NET-CHASSIS", "DOM-MOTOR"),
    ):
        entities[connection.id] = connection

    constraint = TopologyConstraint(
        authored("TOPO-GND"),
        net="NET-GND",
        mode=TopologyMode.STAR,
        center="NET-MOTOR-STAR",
        branches=("DOM-LOGIC", "DOM-MOTOR"),
    )
    failures = [r for r in constraint.verify(entities) if r.status is CheckStatus.FAIL]
    assert failures
    # Intent is distinct from net equivalence: the same net, a different verdict.
    assert failures[0].paths and "NET-CHASSIS" in failures[0].paths[0]


def test_at_k6_one_safe_edit_round_tripped_to_cad():
    """AT-K6: one edit round-trips with no unrelated electrical change."""
    from fang.elaborate import elaborate
    from fang.kicad import emit_netlist, read_netlist
    from fang.netlist import compile_netlist
    from fang.graph import RemoveEntity

    from examples.divider.divider import Divider

    original = elaborate(Divider, project_id=PROJECT)
    before = compile_netlist(original.snapshot, traits=original.traits)
    text = emit_netlist(before, source="divider.py")

    imported = read_netlist(text, project_id=PROJECT, source="divider.net")
    graph = KernelGraph(Snapshot(PROJECT, "REV-IMPORT", imported.entities))

    target = next(
        e for e in imported.entities.values()
        if isinstance(e, Component) and e.designator == "R2"
    )
    edited = Component(
        target.identity,
        designator=target.designator,
        part="22 kOhm",
        package=target.package,
        provenance=target.provenance,
        source_location=target.source_location,
        extensions=target.extensions,
    )
    proposal = graph.apply(
        Transaction(
            graph.head.hash,
            (
                RemoveEntity(target=target.id, reason="replace"),
                AddEntity(entity=edited, reason="set R2 to 22 kOhm"),
            ),
        )
    )
    assert proposal.accepted

    after = compile_netlist(graph.head)
    changed = {
        c.designator: c.value for c in after.components
    } != {c.designator: c.value for c in before.components}
    assert changed
    # Nothing else moved: every net is untouched by a value change.
    assert [(n.name, [(x.designator, x.pin) for x in n.nodes]) for n in after.nets] == [
        (n.name, [(x.designator, x.pin) for x in n.nodes]) for n in before.nets
    ]
    assert {c.designator for c in after.components} == {
        c.designator for c in before.components
    }


def test_at_k7_external_rule_check_results_are_ingested_after_commit_never_before(kernel):
    """AT-K7."""
    stale = kernel.head.hash
    kernel.apply(Transaction(stale, (AddEntity(entity=Component(authored("CMP-Z"))),)))

    # Ingesting against a snapshot that is not the committed head is refused.
    with pytest.raises(FangError):
        ingest_external_results(
            kernel,
            [CheckResult("drc", CheckStatus.PASS, "CMP-Z", "clearances ok")],
            snapshot_hash=stale,
            record_time=FIXED_TIME,
        )

    proposal = ingest_external_results(
        kernel,
        [CheckResult("drc", CheckStatus.PASS, "CMP-Z", "clearances ok")],
        snapshot_hash=kernel.head.hash,
        record_time=FIXED_TIME,
    )
    assert proposal.accepted
    ingested = [e for e in kernel.head.entities.values() if isinstance(e, Evidence)]
    assert any("drc reported PASS" in e.claim for e in ingested)


def test_at_k8_a_semantic_diff_separates_presentation_from_electrical_change(snapshot):
    """AT-K8: and names the invalidated requirements."""
    before = dict(snapshot.entities)
    after = dict(before)

    # A presentation change.
    identity = before[REGULATOR].identity
    after[REGULATOR] = replace(
        before[REGULATOR], identity=replace(identity, display_name="Main Buck")
    )
    presentation = diff(before, after)
    assert not presentation.electrical

    # An electrical change, with a constraint and a requirement behind it.
    electrical_before = dict(before)
    electrical_before["RULE-1"] = Constraint(
        authored("RULE-1"),
        constraint_kind="max_power_dissipation",
        targets=(REGULATOR,),
        expression=le(Ref(REGULATOR, "power_dissipation", WATTS), Literal.of(Quantity.scalar("1", "W"))),
        source="REQ-PWR-001",
    )
    electrical_after = dict(electrical_before)
    electrical_after[REGULATOR] = electrical_before[REGULATOR].with_parameter(
        "power_dissipation", Value.explicit(Quantity.scalar("0.9", "W"))
    )
    changes = diff(electrical_before, electrical_after)
    assert changes.electrical
    assert "REQ-PWR-001" in changes.invalidated


def test_at_k9_a_rejected_agent_proposal_leaves_state_unchanged_and_still_explains(
    kernel, power_constraint
):
    """AT-K9."""
    from fang.provenance import Actor, ActorKind, ProvenanceOrigin, ProvenanceRecord

    agent_origin = ProvenanceRecord(
        ProvenanceOrigin.GENERATED,
        "agent_proposal",
        Actor(ActorKind.MODEL, "copperhead-agent", "1.0"),
        "REV-000001",
        FIXED_TIME,
    )
    head_before = kernel.head.hash
    entities_before = dict(kernel.head.entities)

    proposal = kernel.propose(
        Transaction(
            kernel.head.hash,
            (
                AddEntity(entity=power_constraint),
                SetParameter(
                    target=REGULATOR,
                    name="power_dissipation",
                    value=Value.explicit(Quantity.scalar("0.5", "W")),
                    reason="agent raised dissipation past the hard limit",
                ),
            ),
            origin=agent_origin,
        )
    )

    assert proposal.rejected
    assert kernel.head.hash == head_before
    assert kernel.head.entities == entities_before
    assert proposal.diagnostics          # it still produces its diagnostics
    assert len(proposal.diff) > 0        # and its diff


def test_at_k10_a_simulation_result_names_its_plan_backend_models_and_gaps():
    """AT-K10."""
    from fang.elaborate import elaborate
    from fang.simulation import (
        Assertion,
        RawResult,
        Transient,
        compile_plan,
        normalize,
    )

    from examples.divider.divider import Divider

    result = elaborate(Divider, project_id=PROJECT)
    plan = compile_plan(
        result.snapshot,
        analysis=Transient(stop="10ms", step="10us", probes=["V(1)"]),
        traits=result.traits,
    )
    normalized = normalize(
        plan,
        RawResult("ngspice", "ngspice-43", "", 0, ""),
        assertions=[Assertion("max(V(1)) < 3.5 V", "pass")],
    )
    rendered = normalized.as_dict()

    assert rendered["plan"]["analysis"]["kind"] == "transient"
    assert rendered["backend_version"] == "ngspice-43"
    assert "models" in rendered and "assumptions" in rendered
    assert isinstance(rendered["coverage_gaps"], list)
    # And the pass is a finding, never a proof.
    assert "not proof of physical correctness" in rendered["finding"]["caveat"]
